### ISSUE TITLE
Add and document Acend provided VM setup

### ISSUE THREAD

**Issue by mabegglen** [puzzle/prometheus-training#21]
<https://gitlab.puzzle.ch/pitc_ansible/techlab/setup-techlab>

* Vagrant Setup with setup-techlab 
    * <https://github.com/puzzle/prometheus-labs/blob/main/Vagrantfile>
    * <https://github.com/puzzle/prometheus-labs/blob/feature/add-k8s-setup/Vagrantfile>
* Change `localhost` references in Labs to VM IP/DNS
* Define firewall rules for HTTP traffic (Prometheus, Alertmanager, Grafana)
   * Do we need authentication?
* Port 3000 seems to be in-use already - we either have to see if we need this component or adjust our Grafana setup

<https://gitlab.puzzle.ch/pitc_ansible/techlab/setup-techlab/-/tree/feature/add-minikube>

**Comment by ombre8** [comment]
Port 300 can be used for grafana when merging this: https://gitlab.puzzle.ch/pitc_ansible/techlab/setup-techlab/-/merge_requests/32
