### ISSUE TITLE
Outdated instructions in Task 2.1.4: Metric network interfaces 

### ISSUE THREAD

**Issue by moll-re** [puzzle/prometheus-training#378]
Under [Task 2.1.4: Metric network interfaces ](https://prometheus-training.puzzle.ch/docs/02/labs/21/#task-214-metric-network-interfaces) the guide suggests filtering interfaces starting with `eth`. The current cloudscale VM uses `veth` interfaces.

Instead filter interface names *containing* `eth`, for instance using the updated query
`node_network_info{device=~".*eth.*"}`

**Comment by rekup** [comment]
Thanks for reporting this issue! This is fixed by https://github.com/puzzle/prometheus-training/pull/379
