### ISSUE TITLE
Migrate Vagrant setup away from CentOS 8

### ISSUE THREAD

**Issue by bliemli** [puzzle/prometheus-training#54]
The [provided Vagrantfile](https://github.com/puzzle/prometheus-labs/blob/main/Vagrantfile#L14) is using CentOS 8. We should start thinking about what to use instead.

Background ([Source](https://blog.centos.org/2020/12/future-is-centos-stream/)):

>CentOS Linux 8, as a rebuild of RHEL 8, will end at the end of 2021.

**Comment by phil-pona** [comment]
Vagrant setup was removed, it was never really used
