### ISSUE TITLE
Use {{% param sectionnumber %}} for tasks

### ISSUE THREAD

**Issue by johanngyger** [puzzle/prometheus-training#60]
Example: https://github.com/acend/kubernetes-basics-training/blob/master/content/en/docs/03/_index.md#task--param-sectionnumber-1-create-a-namespace

**Comment by rekup** [comment]
I was not able to find a way to implement this in the solutions section:

```
{{% details title="Task {{% param sectionnumber %}}.2" %}}
text
{{% /details %}}
```
The title is rendered as string `Task {{% param sectionnumber %}}.2` instead of `Task 2.2`

Let's keep this issue open for the time being (IMHO this issue is not super time critical)

**Comment by phil-pona** [comment]
We've discussed the issue last week, there was no straight forward solution to this. We decided to leave the details part as is until we implemented a solution in the shortcode itself
